# fullnameOverride: "my-custom-traffic-app"
replicaCount: 2

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

image:
  repository: sachinthokal/kube-traffic-lens-app
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

app_port:
  type: ClusterIP
  port: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: app.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 228Mi
  requests:
    cpu: 100m
    memory: 128Mi

startupProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 5

env:
  - name: APP_VERSION
    value: "v1.0.0"
  - name: APP_ENVIRONMENT
    value: "Live"