apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-traffic-lens-app.fullname" . }}
  labels:
    {{- include "kube-traffic-lens-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app_port.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "kube-traffic-lens-app.selectorLabels" . | nindent 4 }}
